# production: &production
#   :url: redis://localhost:6379
#   :host: localhost
#   :port: 6379
#   :timeout: 1

local: &local
  :url: <%= ENV.fetch 'REDIS_URL', 'redis://localhost:6379' %> # Fetch environment variable (i.e. Docker Compose example)
  :timeout: 1
  :inline: true
development: *local
test: *local
